apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedulingplugin
  namespace: scheduler-plugins
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
    spec:
      nodeSelector:
        node-role.kubernetes.io/control-plane: ""
      containers:
        - image: romialmenra/scheduler-plugin:latest
          imagePullPolicy: Always
          command:
          - /bin/kube-scheduler
          - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
          - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
          - --config=/etc/kubernetes/energyawarescore-config.yaml
          - -v=9
          name: schedulingplugin
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /etc/kubernetes/scheduler.conf
            name: etckubernetes
            readOnly: true
          - mountPath: /etc/kubernetes/energyawarescore-config.yaml
            name: energyaware-config
            readOnly: true
      hostNetwork: true
      hostPID: false
      resources:
        requests:
          cpu: 100m
      volumes:
      - hostPath:
          path: /etc/kubernetes/scheduler.conf
          type: FileOrCreate
        name: etckubernetes
      - hostPath:
          path: /etc/kubernetes/energyawarescore-config.yaml
          type: File
        name: energyaware-config

